"""Generate docs/compatibility-matrix.md (GOV-01): which versions of the SDK, policy bundle, template, extension and
pinned libraries belong together in one release.

    python scripts/gen_compat_matrix.py            # rewrite docs/compatibility-matrix.md
    python scripts/gen_compat_matrix.py --check    # exit 1 if the file is out of date (CI)

Everything is read from the repository (pyproject files, VERSION, package.json, compose.yaml, versions.json), so the
matrix can't drift from what is actually released.
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "compatibility-matrix.md"


def read_text(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def pins(dependencies: list[str]) -> list[tuple[str, str]]:
    result = []
    for dep in dependencies:
        match = re.match(r"([A-Za-z0-9_.-]+)\s*(.*)", dep)
        if match:
            result.append((match.group(1), match.group(2) or "(any)"))
    return sorted(result)


def render() -> str:
    sdk = tomllib.loads(read_text("sdk/pyproject.toml"))["project"]
    policy_version = read_text("policy/VERSION").strip()
    template_version = re.search(r'TEMPLATE_VERSION = "([^"]+)"', read_text("sdk/src/ent_agent_sdk/devtools/scaffold.py")).group(1)
    extension = json.loads(read_text("vscode-extension/package.json"))
    ts_sdk = json.loads(read_text("sdk-ts/package.json"))
    versions = json.loads(read_text("policy/data/versions.json"))
    compose = read_text("compose.yaml")
    images = sorted(set(re.findall(r"^\s+image:\s*(\S+)", compose, re.M)))

    lines = [
        "# Compatibility matrix", "",
        "Which versions belong together. Generated by `python scripts/gen_compat_matrix.py` from the repository: do not edit",
        "by hand (CI fails if it is out of date).", "",
        "## This release", "",
        "| Component | Version | Where |", "|-----------|---------|-------|",
        f"| Enterprise Agent SDK (Python) | {sdk['version']} | `sdk/pyproject.toml` |",
        f"| Enterprise Agent SDK (TypeScript) | {ts_sdk['version']} | `sdk-ts/package.json` |",
        f"| Policy bundle | {policy_version} | `policy/VERSION` |",
        f"| Project template | {template_version} | `devtools/scaffold.py` (`TEMPLATE_VERSION`) |",
        f"| VS Code extension | {extension['version']} (VS Code {extension['engines']['vscode']}) | `vscode-extension/package.json` |",
        f"| Python | {sdk['requires-python']} | `sdk/pyproject.toml` |", "",
        "## Approved library versions (Python SDK)", "",
        "Pinned with `~=` (patch updates only). Agents depend on `ent-agent-sdk` only and get exactly these.", "",
        "| Library | Pin |", "|---------|-----|",
        *[f"| {name} | `{spec}` |" for name, spec in pins(sdk["dependencies"])], "",
        "## Approved library versions (TypeScript SDK)", "",
        "| Library | Range |", "|---------|-------|",
        *[f"| {name} | `{spec}` |" for name, spec in sorted(ts_sdk["dependencies"].items())], "",
        "## Local runtime images (pinned)", "",
        "| Image |", "|-------|", *[f"| `{image}` |" for image in images], "",
        "## Support windows", "",
        f"Policy: {versions['deprecation'].get('sunset_days_after_successor', 90)}-day sunset after a successor ships; the current and previous "
        "minor series are supported. A repo past its sunset fails CI (ENT-060); within "
        f"{versions['deprecation'].get('warn_days', 90)} days it gets a warning (ENT-061).", "",
        "| Component | Latest | Supported series (sunset date) |", "|-----------|--------|-------------------------------|",
    ]
    for label, key in (("SDK", "sdk"), ("Policy bundle", "policy_bundle")):
        entry = versions[key]
        supported = ", ".join(f"{s['version']} ({s['sunset'] or 'no sunset yet'})" for s in entry["supported"])
        lines.append(f"| {label} | {entry['latest']} | {supported} |")
    lines += ["", "Changes per release: see [CHANGELOG.md](../CHANGELOG.md).", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != text:
            print("docs/compatibility-matrix.md is out of date: run `python scripts/gen_compat_matrix.py`.")
            return 1
        print("Compatibility matrix is up to date.")
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
